### ISSUE TITLE
Crashing on Ayaneo Geek

### ISSUE THREAD

**Issue by dainiax** [Maccraft123/ayaled#3]
Hi,
Using Ayaneo Geek with ChimeraOS (2023.04.20-x86_64)
Installed with "sudo pacman -Sy ayaled"
Output for installation
-----
core is up to date
extra is up to date
community is up to date
multilib is up to date
error: target not found: ayaled
-----

Checking status "systemctl status ayaled" -> "Active: failed"
Status output
-----
Started Aya Neo LED manager.
Using fast-path EC RAM RW.
Found battery at "/sys/class/power_supply/hidpp_battery_0"
thread 'main' panicked at 'Failed to read battery capacity: 0s { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:271:62
note: run with 'RUST_BACKTRACE=1' environment variable to display a backtrace
ayaled.service: Main process exited, code=exited, status=101/n/a
-----

Any ideas what can be an issue or how to fix?
Thank you

**Comment by Maccraft123** [comment]
No idea where to look, especially considering that ayaneo didn't send me a
dev sample of ayaneo geek or ayaneo 2
